services:
  - type: web
    name: ftb-stoic-mentor-site
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
